# Generated by Django 4.0.5 on 2023-03-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeprofile',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
