# Generated by Django 4.0.5 on 2023-03-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='feedback',
        ),
    ]
