# Generated by Django 4.0.5 on 2023-03-25 19:05

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_cart_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='product_id'),
        ),
    ]
