# Generated by Django 4.0.5 on 2023-03-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='modeofdelivery',
            field=models.CharField(default='', max_length=255),
        ),
    ]
