# Generated by Django 4.0.5 on 2023-03-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_orderitem_modeofdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='modeofdelivery',
            field=models.CharField(default='Electric Vehicle', max_length=255),
        ),
    ]
