# Generated by Django 4.0.5 on 2023-03-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_orderitem_delivery_status_orderitem_shipped_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('review', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=255)),
            ],
        ),
    ]
