# Generated by Django 4.0.5 on 2023-03-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
