# Generated by Django 4.0.5 on 2023-03-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_reviews_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
