# Generated by Django 4.0.5 on 2023-03-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_orderitem_order_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('fullName', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
