# Generated by Django 4.0.5 on 2023-03-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_deliveryprofile_orderitem_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devname', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=255)),
            ],
        ),
    ]
