# Generated by Django 4.0.5 on 2023-03-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='devname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
