# Generated by Django 4.0.5 on 2023-03-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_orderitem_devname'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
