# Generated by Django 4.0.5 on 2023-03-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_orderitem_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='mode',
            field=models.CharField(default='Electric Vehicle', max_length=255),
        ),
    ]
