# Generated by Django 4.0.5 on 2023-03-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_remove_cart_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='doh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='dos',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
