# Generated by Django 4.0.5 on 2023-03-25 14:43

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProduct',
            fields=[
                ('prodID', models.AutoField(primary_key=True, serialize=False)),
                ('compName', models.CharField(max_length=255)),
                ('prodName', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField(default=0)),
                ('discPrice', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='prodID')),
                ('coupons', models.CharField(max_length=255)),
                ('ratings', models.IntegerField(default=0)),
                ('feedback', models.CharField(max_length=255)),
                ('stockDetails', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
