# Generated by Django 4.0.5 on 2023-03-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_farmerproduct_farmerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FarmerProduct',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='comp_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='emailAddress',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='fullName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='zipcode',
            field=models.CharField(default='', max_length=255),
        ),
    ]
